
version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: my-redis-container
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.10.7-management

    ports:
      - "15672:15672"
      - "5672:5672"
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
volumes:
  db:
    driver: local
  cache:
    driver: local

